SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.2  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.2
LAZER_SHOOT_COOLDOWN = 0.1

SHOT_RADIUS = 5

POWERUP_RADIUS = 10
POWERUP_DURATION = 20.0
SHIELD_WIDTH = 6
LAZER_WIDTH = 2
LAZER_LENGTH = 13